### ISSUE TITLE
Scrollable.of() Error

### ISSUE THREAD

**Issue by Naveenchand06** [hamaluik/timecop#109]
When I run the app for the first time from the master branch. I'm getting an error saying ```Scrollable.of() was called with a context that does not contain a Scrollable widget```
![WhatsApp Image 2023-03-13 at 10 32 35 PM](https://user-images.githubusercontent.com/82134112/224774026-87ee78e6-1658-4dee-a8b1-8ff6ac5b5e4a.jpeg)

**Comment by 12people** [comment]
@Naveenchand06 Seems to be a problem with the latest Flutter release (3.7) — https://github.com/flutter/flutter/issues/115705

I might look into it later, when I find some time. Of course, feel free to debug this yourself and submit a pull request.

**Comment by 12people** [comment]
Apparently, it has been [fixed in `flutter_typeahead`'s latest version](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/444), but `flutter_slidable` is still [waiting for a fix](https://github.com/letsar/flutter_slidable/issues/402).
