### ISSUE TITLE
add date (and time) to export file name to make it more unique

### ISSUE THREAD

**Issue by grrrrr** [hamaluik/timecop#117]
Currently if you export data from TimeCop  the file name is `timecop.csv` which makes it hard to track when an export is from, or also potentially overwriting existing exports.

It would be useful to have the export file name changed to include a date and possibly time

e.g. timecop-yyyyMMdd-hhmm.csv   to allow multiple exports a day    or more simple   timecop-yyyyMMdd.csv

**Comment by 12people** [comment]
Sure, sounds good. :)
I'd be in favor of timecop-YYYY-MM-DD.csv, respecting the ISO 8601 standard.

Would you be willing to submit a pull request for this?

**Comment by grrrrr** [comment]
ISO 8601 is good,  not sure why I didn't put it in that format.

I have an inkling what needs to be added to ExportScreen.dart but I'm not set up to test it so it'd be done blind :-/

**Comment by 12people** [comment]
Done as part of https://github.com/hamaluik/timecop/commit/29733450ae2f09a7d36b0a8535251c2be8454d52
