### ISSUE TITLE
Add a filter period - current month

### ISSUE THREAD

**Issue by grrrrr** [hamaluik/timecop#122]
Some little but of usability improvement request.

Like a lot of people billing is done on a monthly basis.  To reduce the steps needed to filter on current month (report -> filter -> change month and date) a useful option would be to be able to have the filter show a default option of 1st of the current month.

**Comment by 12people** [comment]
Added in the latest PR.

(Not added yet for exports, that's coming soon. There's more in-progress work being done for exports, which is why that's coming later.)
