### ISSUE TITLE
Making TimeEditor screen scrollable

### ISSUE THREAD

**Issue by vpetrovic01** [hamaluik/timecop#133]
To do - make TimeEditor screen scrollable.
![to_do](https://github.com/hamaluik/timecop/assets/114599665/6e0033c9-f4f8-4e29-8875-c33dfbcd4253)
Fix the issue of overflow on small screens when entering the description of the project.
![greska](https://github.com/hamaluik/timecop/assets/114599665/2f959d2c-db91-4808-babe-2479f4aed2ca)

**Comment by master-wayne7** [comment]
I can work on this issue, can you assign it to me?
