### ISSUE TITLE
Option to add additional information to an event

### ISSUE THREAD

**Issue by usrme** [hamaluik/timecop#15]
First of all, thanks for the wonderful app; already gotten my money's worth!

Secondly, I was wondering if it would be possible to add additional information to an event? I'm currently logging the time I am in various meetings and the ability to quickly add more information other than the single sentence description would be wonderful!

I can see this being useful for more meaningful project work as well as for an event such as "Creating new module" you could add bullet points of smaller tasks within that.

Thanks again and keep up the good work!

**Comment by hamaluik** [comment]
Thanks!

Would adding a single (multiline) edit field work for your use case? You could access it only when editing a timer. I could certainly use this feature myself so will try to get to it soon.

**Comment by usrme** [comment]
Yeah, a single edit field is absolutely fine!

**Comment by hamaluik** [comment]
Added in 018b434
