### ISSUE TITLE
Option to have ongoing notification for ongoing timers

### ISSUE THREAD

**Issue by usrme** [hamaluik/timecop#18]
Many a time have I forgotten to leave a timer going just because I closed the application to go do something else (on the phone). If there was a notification icon that would expand to the event description (maybe also the project under which it is) and the currently elapsed time, then when it would always be there in the periphery or at the very least be something that gets reminded when the phone is opened (as the notification would be visible in the lock screen).

**Comment by hamaluik** [comment]
I'm not as familiar with Android anymore, but I don't believe iOS supports this without continually pinging the user with notifications? This is certainly something I could look at adding however, but I have to think on it more and plan out how it might be done. Thanks!

**Comment by danielpferreira** [comment]
How does one "upvote" a post in github?
I just added a 👍
Is that enough to show I'd also like that feature?

**Comment by hamaluik** [comment]
Added in 8bf6ae37e2fd48d6800b2757096a0a4444c36944

**Comment by danielpferreira** [comment]
Thanks for adding this!

However the notification only mentions there are Running Timers, but doesn't specify which, or what is the elapsed time (which means it's not very useful).

I'm on Android.

**Comment by danielpferreira** [comment]
@hamaluik should I add a new Issue with the request above?
(Not sure if Closed issues are still being considered)

**Comment by drawtheliner** [comment]
Also the notification persists even once all timers are stopped. Android.

@hamaluik could you please confirm you read these, and that this is helping (and/or being considered) in any way? If not I can just stop suggesting things, no problem.
