### ISSUE TITLE
Project archiving

### ISSUE THREAD

**Issue by danielpferreira** [hamaluik/timecop#22]
I just started trying out Time Cop and really like it so far.

I love the simple/lightweight approach, however I did miss a feature that I'd need to be able to continue using it long-term: the ability to archive projects that I'm done with. 

At any given time I usually have around 5 projects which are Ongoing (stuff I'll always have, such as Admin work), and then around 5 more which eventually get finished. As I use the app, eventually these projects will clutter up the list, making it too difficult to navigate.

Any plans on including some (minimal) Project archiving feature?

**Comment by hamaluik** [comment]
I could definitely use this myself. Thanks for the suggestion, I'll try to get to it soon!

**Comment by hamaluik** [comment]
Added in 72f6489
