### ISSUE TITLE
Option to append Project Name to Description

### ISSUE THREAD

**Issue by drawtheliner** [hamaluik/timecop#23]
Would be great to have the option to enable showing the Project name in front of the Description.

So that:
🟠 Testing
🟡 Meeting
🔴 Sketching
🟡 Phone call

Becomes:
🟠 **Samsung:** Testing
🟡 **Uncle:** Meeting
🔴 **Personal:** Sketching
🟡 **Uncle:** Phone call

For me it's hard to remember the color for every single project. Descriptions are usually very minimal (as they should be), so it's hard to tell just by looking at them.

I appreciate that some users working with fewer projects wouldn't have this problem, and would prefer not to waste that space. Maybe just add this as an option in Settings. (People who decide to enable it would probably use shorter project names anyways)

Implementation itself wouldn't need (I think) to add any new elements to the UI. Project name could be appended to start of the text field currently showing the Description (ideally in bold, like in my example above). Just a suggestion, of course!

**Comment by 12people** [comment]
There will be a new "Show Project Names" setting in the next release.
