### ISSUE TITLE
Search: two suggestions

### ISSUE THREAD

**Issue by danielpferreira** [hamaluik/timecop#31]
1. Currently two taps are needed for searching. One to bring up the search input field, then one in the field itself to prompt the keyboard. Any way to make this happen directly, with one tap?

2. Search field is very hard to read on the dark background, as it uses dark font. I suggest the icon and text be a lighter color.

Search isn't something I though I'd be using. But since I usually start a new timer based on a previous one, I found the easier way is by Searching for it, then starting it from there. I'd rather do this directly in the bottom input text field, by tapping the options given by autocomplete. However, as I mentioned before, doing that doesn't populate the Project field, only the Description.

**Comment by hamaluik** [comment]
Fixed!
