### ISSUE TITLE
Search issues (though autocomplete works fine)

### ISSUE THREAD

**Issue by danielpferreira** [hamaluik/timecop#33]
The search (on top) isn't finding certain entries - seems to happen only for older ones.

On the other hand, autocomplete in the New Entry field always seems to find what I want. (though I then need to add the Project)

Let me know if you want any further info.

**Comment by hamaluik** [comment]
Would it happen to be entries that are older than 30 days?

**Comment by danielpferreira** [comment]
Yes. I did a related post more recently that addresses that:

https://github.com/hamaluik/timecop/issues/39

**Comment by hamaluik** [comment]
The search is limited by the currently applied filter. So, you can search earlier than a month back, so long as the filter you've set up allows that.

I agree that it isn't quite intuitive, but am closing this in favour of solving the problem in #39
