### ISSUE TITLE
Exported Timecop data does not escape commas

### ISSUE THREAD

**Issue by bxbrenden** [hamaluik/timecop#34]
### Description
Timecop exports its data in `csv` format. The UI lets users add commas to their `what are you doing?` descriptions. When Timecop exports data to `csv` it leaves those commas intact and unescaped. This breaks the `csv` format by changing the number and alignment of columns.

### Request
Add an option in the `Options` part of the `Export` menu to specify some kind of escape characters such as double quotes around the `Description` field. There's some info about escaping commas in the [official csv RFC](https://tools.ietf.org/html/rfc4180) that might be useful.

**Comment by hamaluik** [comment]
Would an acceptable solution be to just always delimit all of the fields? If so, I enabled this in d09c6c8

**Comment by bxbrenden** [comment]
@hamaluik does that build exist anywhere on the Apple App Store? The last version I see available for iOS is from 8 months ago.

**Comment by hamaluik** [comment]
Not yet. Fixing a handful more things and then I’ll push the update.
