### ISSUE TITLE
Update plans?

### ISSUE THREAD

**Issue by danielpferreira** [hamaluik/timecop#37]
@hamaluik , do you plan to address the feedback and bug reports we've added in the past several months?

At the time I purchased Time Cop, it was the best tool around. However the lack of updates is making me consider looking for new tools. I'd rather not, since I really like your app!

To be clear, I'm not complaining or trying to pressure you or anything like it! I'm really just asking what are your plans, so I can decide what to do.

**Comment by hamaluik** [comment]
Apologies for being MIA most of the year. I just got an OSX VM back up and running and I believe I'll have some time over the holidays to actually dig into this project again. No promises, but I'm aimiing to have at least some of the issues and pull requests sorted and merged and released within the next few weeks.

Thanks for your patience!

**Comment by danielpferreira** [comment]
Cool! Thanks for the update.
