### ISSUE TITLE
Allow changing default time span for the search (Feature request)

### ISSUE THREAD

**Issue by danielpferreira** [hamaluik/timecop#39]
The search on top seems to be limited to a month back by default (to make sure most users won't run into performance issues, I figure?).

I'm glad that I can override that to a longer span if I need to. But that always reverts back after I've done other operations in the app.

Usually I'd want the default span to be longer. So if there were an option for manually defining this default, it would be very useful!

**Comment by hamaluik** [comment]
Added an option for default search days in the settings in fa5410c

**Comment by danielpferreira** [comment]
The app just updated for me, and all my projects seem to be gone.
Existing time entries are there, but with no color (I figure they aren't
connected to any projects, since they're gone).
How do I recover my project list?

(Haven't tested the new features yet)

**Comment by danielpferreira** [comment]
I tried using the new time span setting, but it doesn't seem to be working.

As before, typing on the bottom field (new Timer) does search further back.
But the top search field is still limited by the filter (ie., ignoring the time span I put in settings)
