### ISSUE TITLE
Lost project data and export issues

### ISSUE THREAD

**Issue by sammyhoworth** [hamaluik/timecop#40]
Hello,
Earlier today I lost all my project data: current and old timers are still available, however everything is now listed as "no project" and all my saved projects were removed. 

Additionally, when I export my data to CSV, only those timers which were previously listed as "no project" get exported, even though now all the timers appear as "no project". 

I remade some projects and assigned them to old timers, however upon re-opening the app the projects were gone and the timers were set back to "no project"

**Comment by sammyhoworth** [comment]
And of course, I just had to update my OS. 
Appreciate the app!

**Comment by danielpferreira** [comment]
I have the same issue.

Why was this issue closed?
Did you find a solution?

(My OS doesn't need updating)

**Comment by sammyhoworth** [comment]
Hello,

Yes I believe I added a comment when closing it. It was simply that I had
to update my phone's OS!

Thanks,
Sammy
