### ISSUE TITLE
Best way to clear database up until a certain date?

### ISSUE THREAD

**Issue by drawtheliner** [hamaluik/timecop#46]
After a little over a year using TimeCop I'd like to backup my existing entries and start anew.

To keep it tidy, I'd like to backup only the exact first year (ie. from 2020/04/01 to 2021/04/01), and keep all entries after that in the app (ie. from 2021/04/02 till today).

What would be the best way to do that?

I was hoping to be able to export only the more recent entries, then re-import it in a way that replaces the current database. But I wasn't able to reimport the database (see my previous issue).

Thanks.

**Comment by hamaluik** [comment]
There isn't a way in the app to do it; the best way to accomplish what you want would be as you say: to export the database, process it however you wish, then import it back in. If you don't know SQL, you could use [DB Browser for SQLite](https://sqlitebrowser.org/) to edit it essentially as a spreadsheet.
