### ISSUE TITLE
Allow crowdsourcing translations using Weblate

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#52]
Weblate is a free and open-source translation platform and it provides [free hosting for FOSS projects](https://weblate.org/en/hosting/#libre). It also [supports the Fluent translation format](https://docs.weblate.org/en/latest/formats.html#fluent-format) that TimeCop uses.

[Hundreds of open-source projects](https://hosted.weblate.org/) use this free option (including one of mine) and it'd be great to be able to contribute translations via an online WYSIWYG interface like this.

**Comment by comradekingu** [comment]
Great idea. Please merge https://github.com/hamaluik/timecop/pull/53 beforehand :)

**Comment by 12people** [comment]
Just created a Weblate project to make it easier to contribute translations: https://hosted.weblate.org/projects/timecop/ .
Now it's waiting for Libre hosting approval.

@hamaluik fyi

**Comment by 12people** [comment]
Libre hosting has been approved!
