### ISSUE TITLE
press enter to start activity

### ISSUE THREAD

**Issue by Simon-Laux** [hamaluik/timecop#60]
would save time on desktop and when using with connected Bluetooth keyboard.

**Comment by Aryashakya** [comment]
I would like to work on this issue.

**Comment by 12people** [comment]
@Aryashakya Great!

If you have questions, feel free to write here or to DM me.

**Comment by Aryashakya** [comment]
I added the start timer functionality to the onSubmitted function of Description TextField. Could you please review it?

#76

**Comment by 12people** [comment]
Will be part of the next release

Thanks a lot, @Aryashakya !
