### ISSUE TITLE
Cant install on android 12

### ISSUE THREAD

**Issue by Horhik** [hamaluik/timecop#63]
Android 12, LineageOS

[![Screenshot_20220507-115449_F-Droid.png](https://user-images.githubusercontent.com/46262811/167247076-535ea588-2e1e-48c8-a058-2de4eefd59e8.png)

**Comment by 12people** [comment]
The minSdkVersion is 16 (= Android 4.1) and the targetSdkVersion is 31 (Android 12), so I don't think it's that unless Lineage OS reads these differently than stock Android.

The app installs fine for me from inside F-Droid on my (non-rooted OEM) Android 10 device, so I'm not sure what could be going wrong here.

Could you post the logs from logcat?

**Comment by Horhik** [comment]
@12people ![Uploading w2{97f2a4c} (1f85fcb6-c25d-4a35-b400-54ac7a9da5b4 id=0x7f0a03bc tag=BaseCommentFragment) …]()

**Comment by 12people** [comment]
Should be fixed in the latest release. Now we just have to wait for the F-Droid bot to package it up and distribute it.
