### ISSUE TITLE
How delete a task for Linux?

### ISSUE THREAD

**Issue by samkcdev** [hamaluik/timecop#68]
Sorry to ask this basic question. After completing a task I can't find any option to delete it from the list. When clicked on the task it goes to the edit mode. Please let me know how to delete a task. 
It would be better if a delete icon was added next to the completed task. I am using this app in POP OS.

**Comment by 12people** [comment]
@samkcdev Try horizontally scrolling on the task or clicking and dragging the task to the side. There are invisible swipe actions that enable this sort of thing.

Unfortunately, the UI hasn't been optimized to work well with non-touch input.

**Comment by samkcdev** [comment]
Thanks! @12people _clicking and dragging the task to the right side shows the delete icon._ .
