### ISSUE TITLE
Allow users to permanently set a theme

### ISSUE THREAD

**Issue by l3s2d** [hamaluik/timecop#7]
Might require a settings page. Related, consider adding an AMOLED theme.

Wonderful app, thank you.

**Comment by hamaluik** [comment]
This shouldn’t be too difficult. It actually started that way and I removed that function. By AMOLED theme do you mean a theme with more pure black?

**Comment by l3s2d** [comment]
Exactly. If you need some reference, the following apps (on Android) all have an AMOLED/black theme: Bitwarden, Wikipedia, Slide for Reddit, Aegis, Facebook Messenger, and NewPipe.
