### ISSUE TITLE
problem deleting project

### ISSUE THREAD

**Issue by vasquezalvaro** [hamaluik/timecop#71]
message recieved:
_CastError (type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast)
ProjectScreen.dart. line 119

**Comment by 12people** [comment]
@vasquezalvaro Which version was this in?

**Comment by vasquezalvaro** [comment]
name: timecop
description: Simple private time tracking.
version: 1.7.2+43
publish_to: none

I am compiling for MacOs(Darwin) with Flutter: 3.3.0

**Comment by vasquezalvaro** [comment]
I downloaded the last source in master.
Thanks for your replay.

**Comment by 12people** [comment]
@vasquezalvaro 
Just pushed the commit https://github.com/hamaluik/timecop/commit/275663fecd3124319c61fde4fed33100d4bfcccd that should hopefully fix the problem.

Thanks for bringing this to my attention!

**Comment by 12people** [comment]
Great, happy to hear that! :)
