### ISSUE TITLE
Timer editing error

### ISSUE THREAD

**Issue by vasquezalvaro** [hamaluik/timecop#72]
Editing Timer Problem

When a project is archived and I try to edit a timer associated with it, the app shows (Dropdown.dart) this error:

Exception has occurred.

_AssertionError ('package:flutter/src/material/dropdown.dart': Failed assertion: line 890 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1': There should be exactly one item with [DropdownButton]'s value: Project(5, Berlinale 2023, Color(0xffe91e63), true). 

Either zero or 2 or more [DropdownMenuItem]s were detected with the same value)

Timecop version: 1.7.2
name: timecop description: Simple private time tracking. version: 1.7.2+43 publish_to: none
I am building for MacOs(Darwin) with Flutter: 3.3.0

Why a timer associated with an archived project appears in timers list?
Thanks for your attention.
<img width="649" alt="Screen Shot 2022-09-07 at 6 19 46 PM" src="https://user-images.githubusercontent.com/2814130/189001269-60896b57-9083-480f-bc05-9f094567f5ec.png">

<img width="653" alt="Screen Shot 2022-09-07 at 6 20 03 PM" src="https://user-images.githubusercontent.com/2814130/189001307-83265493-e16a-4f2f-863e-88a117195210.png">

**Comment by vasquezalvaro** [comment]
more information...
[timecop.csv](https://github.com/hamaluik/timecop/files/9525800/timecop.csv)
<img width="868" alt="Screen Shot 2022-09-08 at 4 56 53 AM" src="https://user-images.githubusercontent.com/2814130/189093635-072c00ed-bdaa-4664-a0cf-d673e010ca6b.png">
<img width="873" alt="Screen Shot 2022-09-08 at 4 57 12 AM" src="https://user-images.githubusercontent.com/2814130/189093721-16d60b9b-8d21-4c3c-854d-c0f99f62fb1c.png">

**Comment by 12people** [comment]
Thanks :)
It should be fixed with this commit: https://github.com/hamaluik/timecop/commit/0075feca2933d59d0deb2ca82e020c907a4f188e

**Comment by vasquezalvaro** [comment]
Thanks a lot. !! You are THE BEST.
