### ISSUE TITLE
A suggestion.

### ISSUE THREAD

**Issue by vasquezalvaro** [hamaluik/timecop#73]
A suggestion:

in ExportMenu.dart

Change lines with
scaffoldKey!.currentState!.showSnackBar(SnackBar(

for
 ScaffoldMessenger.of(context).showSnackBar(SnackBar(

That is because I received dart errors with first line.

**Comment by vasquezalvaro** [comment]
"message": "The method 'showSnackBar' isn't defined for the type 'ScaffoldState'. Try correcting the name to the name of an existing method, or defining a method named 'showSnackBar'.",

**Comment by 12people** [comment]
Done in the latest commit :)
