### ISSUE TITLE
An alternative "comfortable" view

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#78]
To show project names along with tasks (solving #17) as well as to enable a quicker way to pick up older tasks even on mobile, it'd be nice to have a less dense view as an alternative to the current compact view.

Here's a wireframe for this new view:
![Home  complex view](https://user-images.githubusercontent.com/7361228/194776630-1a6b7e01-f1d6-4d79-9b79-e7e5d7f67b2d.png)

The view would only affect the task list and could be toggled on or off in settings.

**Comment by 12people** [comment]
Integrating https://github.com/hamaluik/timecop/issues/98, this view should also integrate start and end times:
![Home  complex view](https://user-images.githubusercontent.com/7361228/202223253-262e0886-aad8-418c-910b-a54cef939f11.png)

**Comment by lucagonzalez** [comment]
Hey @12people anyone working on this?

**Comment by 12people** [comment]
@lucagonzalez Not that I know of.
Is this something you'd like to work on?

BTW, for desktops, I implemented this "richer" view — that's in Master now:
<img width="1440" alt="image" src="https://github.com/hamaluik/timecop/assets/7361228/67eff6fa-902b-4528-8c16-f2aa3183734e">

But that's something quite different than what I proposed here...

**Comment by lucagonzalez** [comment]
Yes, I would like to work on this view.

I think the "richer" view on desktop can benefit from having the project the task belongs to, like the first wireframe of this issue:

> ![Home complex view](https://user-images.githubusercontent.com/7361228/194776630-1a6b7e01-f1d6-4d79-9b79-e7e5d7f67b2d.png)

and if the desktop already has the start and end times, I can implement that on mobile too, finishing the view.

**Comment by 12people** [comment]
Sounds good to me! Feel free to start working on this.

I would call the setting "Show Project Names" rather than "Comfortable view", which I used here.

I would ask you to please implement it along with the start and end times, as shown in the second wireframe:
![image](https://github.com/hamaluik/timecop/assets/7361228/a461d55b-a624-47b2-aec3-d4ec2563e632)

**Comment by lucagonzalez** [comment]
I am making some progress with this view, let me know what you think:

![simulator_screenshot_4EC48E29-0292-45BB-8935-F73BB05F21CB](https://github.com/hamaluik/timecop/assets/34002560/7db3a3a5-65ef-410e-aeeb-121d1e3b755c)

**Comment by lucagonzalez** [comment]
I am making some progress on this view, let me know what you think:

![image](https://github.com/hamaluik/timecop/assets/34002560/68028051-ab9b-4b0e-aae4-769928d12e27)

I still need to do the grouping view and properly add the setting. I think that one will be the hardest thing to do since I've never used BLOC architecture 😅

**Comment by 12people** [comment]
hey @lucagonzalez 

Looks great! Thanks for working on this! I might just adjust the colors a bit once you push it upstream, maybe change the alignment a bit.

As for the Play button — I have it there for discoverability reasons as well as for potential desktop usage. Leave it there for now, I'll see how well it works and potentially remove it myself if it's a problem.

As for BLOC, I'm unfortunately new to it as well. But hopefully this new setting will be similar enough to other settings that we can just look at what we do for them.

Great work, thanks again!
