### ISSUE TITLE
Ask for notification permission

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#81]
When the user first toggles the "Show Running Timer Notifications" setting, ask them for permission to send notifications.

**Comment by 12people** [comment]
Try it in an Android 13 emulator. I tried it and it seems that notifications are disabled by default there.

That's because Android 13 introduced notification permissions: https://developer.android.com/develop/ui/views/notifications/notification-permission .

What might suffice is adding `POST_NOTIFICATIONS` to the manifest, but I haven't tested that yet.

**Comment by 12people** [comment]
The permission should only appear when toggling "Show running timer notifications". That switch should not be allowed to turn on if the relevant permission isn't given.

It could be useful to show a dialog telling the user that they need to enabled that permission, ideally with a link to settings, if the permission is rejected at first. This is an edge case, though (I can't imagine many people turning on a notification setting, then rejecting notifications), so such a dialog would be strictly nice-to-have, but not necessary.

**Comment by AdiAr11** [comment]
Okay, So I can add a check that if notification permission is not given, a dialog box will open asking the user to be taken to the app settings so that they can turn on the notifications.

**Comment by AdiAr11** [comment]
I'll try for the android 13. I'm a little low on storage so I had to uninstall the android emulator.

**Comment by 12people** [comment]
The most important thing is to ask for permission on Android 13 when the setting is toggled.

If it's no longer possible to ask, there should be a dialog saying "Notifications are disabled for Time Cop. Turn them on in Settings → Apps & Notifications → Time Cop → Notifications.". The link to settings is strictly a nice-to-have, though, not a necessity to complete this task. :)

**Comment by AdiAr11** [comment]
Understood. I'll try to install the emulator again😃

**Comment by 12people** [comment]
@AdiAr11 Turns out, there's information on this in the notification package's README: https://pub.dev/packages/flutter_local_notifications#requesting-permissions-on-android-13-or-higher

Seems fairly simple to implement

**Comment by AdiAr11** [comment]
@12people I checked it. Agreed that it looks pretty easy to implement. I won't be able to test it but I will still try to complete it.

**Comment by m4n4n-j** [comment]
Hi!
If it is not resolved, I want to try my hands on this issue.
