### ISSUE TITLE
Debug low-contrast elements

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#83]
It seems like expansion arrows lose their color when expanded:
![image](https://user-images.githubusercontent.com/7361228/195103622-1060d3c7-a0b6-4f6f-b24a-622da9028919.png)

Also, text field labels take on a low-contrast color when clicked:
![image](https://user-images.githubusercontent.com/7361228/195103457-3833b42d-f6ed-4c64-874a-9f26b2ad17b3.png)

It'd be good to go through the UI and fix these low-contrast colors. Ideally inside of [the app themes](https://github.com/hamaluik/timecop/blob/master/lib/themes.dart), if possible.

**Comment by aismaniotto** [comment]
Hi, in the cases of the arrow, should keep the same color, right?

And in the labels case, also should keep the same color or some other?

Can you assign me this issue? thks

**Comment by 12people** [comment]
Your PR looks excellent, thanks!
