### ISSUE TITLE
Upgrade to latest flutter_bloc version

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#84]
The current version of the [flutter_bloc](https://pub.dev/packages/flutter_bloc) library that's being used is 7.3.3, but the latest version is 8.1.1.

For upkeep, it'd be good to upgrade to the latest version, including all the refactoring that takes.

**Comment by Aryashakya** [comment]
I would like to work on this.

**Comment by 12people** [comment]
Absolutely, you'd be more than welcome to. :)

**Comment by Aryashakya** [comment]
The [flutter_bloc](https://pub.dev/packages/flutter_bloc) library was upgraded and the `mapEventToState` was changed to `on<Event>`

Could you review it? #86

**Comment by 12people** [comment]
Excellent, thanks for the pull request!
