### ISSUE TITLE
Fix BuildContexts across async gaps

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#85]
There's a number of warnings throughout the code about using BuildContexts across asynchronous gaps. It'd be good to fix the underlying problems.

For information on why this is happening and how to fix it, see this video: https://www.youtube.com/watch?v=bzWaMpD1LHY

**Comment by AdiAr11** [comment]
Hi, can I work on this issue?

**Comment by 12people** [comment]
@AdiAr11 As you were the first one to ask, I'm assigning this issue to you.

It also seems like another person is interested in working on this, so if you lose interest, please let me know so that I can reassign this issue.

Thanks for contributing. :)

**Comment by AdiAr11** [comment]
Sure, Thank you @12people. I'll get on this asap.

**Comment by AdiAr11** [comment]
I don't see the linter warning for this. Should I add the flutter_lints as well?

**Comment by 12people** [comment]
@AdiAr11 That's strange. Perhaps you have an older version of the code? In master, `flutter_lints` are in `pubspec.yaml` and they're also referenced in `analysis_options`. I see warnings on this on my side, so I'm not sure why you're not seeing them.

**Comment by AdiAr11** [comment]
Strange. I'll check if i have taken the latest pull.

**Comment by 12people** [comment]
@AdiAr11

On an unrelated note, please take a look at my comment for another person's PR related to this: https://github.com/hamaluik/timecop/pull/87#issuecomment-1279932673

It contains information that's relevant for you too. And I should mention that not all of these warnings need to be fixed right away — in some places, it might be advisable to just add a comment and wait until the [`context.mounted` property](https://twitter.com/remi_rousselet/status/1570794942251016192) is added for StatelessWidgets.

**Comment by AdiAr11** [comment]
Yes I saw that. I'll keep that in mind. Thank you !!

**Comment by AdiAr11** [comment]
Also saw that my fork was way behind. Have updated it.

**Comment by 12people** [comment]
Great, thanks for the PR!

There were just two things I would do differently and I submitted commits with fixes already:
- In ExportScreen, instead of checking for `mounted`, the Share dialog should appear even if the user has navigated elsewhere: https://github.com/hamaluik/timecop/commit/6a504dd96b96affd76808fe85f1b26a59df8cd2f
- In ExportMenu, you were creating new variables just to assign them to existing variables, unnecessarily: https://github.com/hamaluik/timecop/commit/6208dab93a121d11625ad85c678fd0b88d5f1c27

Just as a tip for next time. :)

Thanks again!

**Comment by AdiAr11** [comment]
Thank you so much. I'll take a look at the changes you made as well for future references. Thank you !!
