### ISSUE TITLE
Starting another timer doesn't stop the running one

### ISSUE THREAD

**Issue by 1over137** [hamaluik/timecop#91]
With "Only Allow One Running Timer at a Time" set to ON in the settings, I expect it to stop the currently running timer when I start another one by swiping left on a previous task. This does not happen, and both timer runs at the same time as a result.

**Comment by 12people** [comment]
Completely agree that starting another timer in this mode should automatically stop the previous timer.

**Comment by 12people** [comment]
@lucagonzalez 
Sure, go ahead :)

**Comment by 12people** [comment]
@lucagonzalez 
Looks great, thanks a lot!

Could you also take care of the instances where a timer gets created in the `DescriptionField.dart` file?

**Comment by lucagonzalez** [comment]
@12people 
Just pushed!
