### ISSUE TITLE
Add a Material You theme with dynamic colors

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#92]
Use the [`dynamic_color` package](https://pub.dev/packages/dynamic_color) to add a Material You theme as an option for the app.

The theme can only be for light mode for now, dark mode can be implemented in a subsequent issue.

**Comment by 15jgme** [comment]
Hey @12people, I can take a look at this in the next few weeks if it's still of interest

**Comment by 12people** [comment]
@15jgme Sure thing. :)

Just please add it as an additional theme option, don't modify any existing themes.

**Comment by 12people** [comment]
(Also, Hacktoberfest is now over, so there is no possibility to get any rewards from that contest anymore.)

**Comment by 15jgme** [comment]
Sounds good i'll make sure it's only an addition. 
And no worries, I know it ended, I just want to help out :)

**Comment by 12people** [comment]
Awesome, thanks for the support!

**Comment by 12people** [comment]
Will be in the next release.
