### ISSUE TITLE
View with start and end time 

### ISSUE THREAD

**Issue by mjjzf** [hamaluik/timecop#98]
In my organization, we enter the work time in a form. 
The app would be even more useful if start and end time would be featured in the overview, possibly with a column chooser like in the reporting section.

**Comment by 12people** [comment]
@mjjzf There was a separate request to show project names as well, leading to a "complex view" proposal in #78 . This complex view could potentially show start and end times too:

![Home  complex view](https://user-images.githubusercontent.com/7361228/202223767-7f634f70-4c89-441e-92a3-82d921e6965c.png)

**Comment by 12people** [comment]
That said, I don't think I'll find the time in the near future to work on this. So I'm leaving this up for potential contributors who might like to try their hand at an implementation.

If this feature is important to you, you're more than welcome to submit a pull request. :)

**Comment by 12people** [comment]
Implemented on mobile as part of the "Show Project Names" feature and on larger screen sizes in general.
Will be in the next release.
